### PR TITLE
[12.0] database_block + database_limit_size backport

### PR DESCRIPTION
**Pull request by em230418**
На основе https://github.com/itpp-labs/access-addons/pull/238

### CODE REVIEW

**Comment by trojikman** [comment]
:heavy_check_mark: database_expiration

**Comment by em230418** [comment]
Заодно это еще запушил: https://github.com/itpp-labs/access-addons/pull/239

**Review by trojikman — CHANGES_REQUESTED** [review]
https://github.com/itpp-labs/access-addons/pull/255/checks?check_run_id=1516977181#step:15:130

**Review by trojikman — APPROVED** [review]
Всё работает

**Comment by trojikman** [comment]
I approve to merge it now

**Pull request merged**
